<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            // Finance Department (2)
            ['nik' => '12345678901234567890', 'no_ktp' => '3171234567890123', 'nama' => 'Budi Santoso', 'department' => 'Finance', 'jabatan' => 'Manager', 'tempat_lahir' => 'Jakarta', 'tanggal_lahir' => Carbon::create(1985, 5, 15), 'tanggal_masuk' => Carbon::create(2015, 3, 1), 'jenis_kelamin' => 'L', 'dept_on_line' => 'Finance', 'dept_on_line_awal' => 'Finance', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 2, 'status_pajak' => 'K/2', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Sudirman No. 123, Jakarta Selatan 12920', 'alamat_domisili' => 'Jalan Gatot Subroto No. 456, Jakarta Selatan 12920', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp', 'foto_ijazah' => 'path/to/ijazah']), 'data_kepribadian' => json_encode(['mbti' => 'ESTJ', 'disc' => 'D']), 'ai_metrics' => json_encode(['turnover_risk' => 0.15, 'performance_score' => 8.5])],
            ['nik' => '12345678901234567891', 'no_ktp' => '3171234567890124', 'nama' => 'Siti Nurhaliza', 'department' => 'Finance', 'jabatan' => 'Staff Accounting', 'tempat_lahir' => 'Bandung', 'tanggal_lahir' => Carbon::create(1990, 8, 22), 'tanggal_masuk' => Carbon::create(2018, 6, 15), 'jenis_kelamin' => 'P', 'dept_on_line' => 'Finance', 'dept_on_line_awal' => 'Finance', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 1, 'status_pajak' => 'K/1', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Gatot Subroto No. 456, Jakarta Selatan 12920', 'alamat_domisili' => 'Jalan Gatot Subroto No. 456, Jakarta Selatan 12920', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ISTJ', 'disc' => 'C']), 'ai_metrics' => json_encode(['turnover_risk' => 0.08, 'performance_score' => 8.8])],
            // IT Department (4)
            ['nik' => '12345678901234567892', 'no_ktp' => '3171234567890125', 'nama' => 'Rudi Hermawan', 'department' => 'IT', 'jabatan' => 'Developer', 'tempat_lahir' => 'Surabaya', 'tanggal_lahir' => Carbon::create(1992, 10, 5), 'tanggal_masuk' => Carbon::create(2018, 1, 15), 'jenis_kelamin' => 'L', 'dept_on_line' => 'IT', 'dept_on_line_awal' => 'IT', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Lajang', 'jumlah_anak' => 0, 'status_pajak' => 'TK/0', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Ahmad Yani No. 789, Surabaya 60123', 'alamat_domisili' => 'Jalan Pemuda No. 100, Jakarta Pusat 10130', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'INTP', 'disc' => 'C']), 'ai_metrics' => json_encode(['turnover_risk' => 0.35, 'performance_score' => 8.2])],
            ['nik' => '12345678901234567893', 'no_ktp' => '3171234567890126', 'nama' => 'Adi Wijaya', 'department' => 'IT', 'jabatan' => 'Senior Developer', 'tempat_lahir' => 'Medan', 'tanggal_lahir' => Carbon::create(1988, 3, 20), 'tanggal_masuk' => Carbon::create(2016, 7, 1), 'jenis_kelamin' => 'L', 'dept_on_line' => 'IT', 'dept_on_line_awal' => 'IT', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 2, 'status_pajak' => 'K/2', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Merdeka No. 456, Medan 20112', 'alamat_domisili' => 'Jalan Benda No. 200, Jakarta Selatan 12310', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ENTJ', 'disc' => 'D']), 'ai_metrics' => json_encode(['turnover_risk' => 0.12, 'performance_score' => 9.0])],
            ['nik' => '12345678901234567894', 'no_ktp' => '3171234567890127', 'nama' => 'Citra Dewi', 'department' => 'IT', 'jabatan' => 'DevOps Engineer', 'tempat_lahir' => 'Jakarta', 'tanggal_lahir' => Carbon::create(1994, 4, 10), 'tanggal_masuk' => Carbon::create(2019, 5, 15), 'jenis_kelamin' => 'P', 'dept_on_line' => 'IT', 'dept_on_line_awal' => 'IT', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Lajang', 'jumlah_anak' => 0, 'status_pajak' => 'TK/0', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Kuningan No. 789, Jakarta Selatan 12950', 'alamat_domisili' => 'Jalan Kuningan No. 789, Jakarta Selatan 12950', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ISTP', 'disc' => 'C']), 'ai_metrics' => json_encode(['turnover_risk' => 0.25, 'performance_score' => 8.6])],
            ['nik' => '12345678901234567895', 'no_ktp' => '3171234567890128', 'nama' => 'Fajar Rahman', 'department' => 'IT', 'jabatan' => 'QA Engineer', 'tempat_lahir' => 'Bandung', 'tanggal_lahir' => Carbon::create(1995, 7, 18), 'tanggal_masuk' => Carbon::create(2020, 9, 1), 'jenis_kelamin' => 'L', 'dept_on_line' => 'IT', 'dept_on_line_awal' => 'IT', 'status_pkwtt' => 'KONTRAK', 'status_keluarga' => 'Lajang', 'jumlah_anak' => 0, 'status_pajak' => 'TK/0', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Gatot Subroto No. 200, Bandung 40272', 'alamat_domisili' => 'Jalan Jatinegara No. 300, Jakarta Timur 13310', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ISTJ', 'disc' => 'C']), 'ai_metrics' => json_encode(['turnover_risk' => 0.40, 'performance_score' => 7.9])],
            // HR Department (2)
            ['nik' => '12345678901234567896', 'no_ktp' => '3171234567890129', 'nama' => 'Dina Wijaksana', 'department' => 'Human Resources', 'jabatan' => 'HR Manager', 'tempat_lahir' => 'Jakarta', 'tanggal_lahir' => Carbon::create(1987, 7, 12), 'tanggal_masuk' => Carbon::create(2016, 6, 15), 'jenis_kelamin' => 'P', 'dept_on_line' => 'Human Resources', 'dept_on_line_awal' => 'Human Resources', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 1, 'status_pajak' => 'K/1', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Kuningan No. 789, Jakarta Selatan 12950', 'alamat_domisili' => 'Jalan Kuningan No. 789, Jakarta Selatan 12950', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ESFJ', 'disc' => 'I']), 'ai_metrics' => json_encode(['turnover_risk' => 0.10, 'performance_score' => 8.7])],
            ['nik' => '12345678901234567897', 'no_ktp' => '3171234567890130', 'nama' => 'Rina Susanti', 'department' => 'Human Resources', 'jabatan' => 'Recruiter', 'tempat_lahir' => 'Bandung', 'tanggal_lahir' => Carbon::create(1994, 2, 14), 'tanggal_masuk' => Carbon::create(2019, 4, 1), 'jenis_kelamin' => 'P', 'dept_on_line' => 'Human Resources', 'dept_on_line_awal' => 'Human Resources', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Lajang', 'jumlah_anak' => 0, 'status_pajak' => 'TK/0', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Gatot Subroto No. 200, Bandung 40272', 'alamat_domisili' => 'Jalan Jatinegara No. 300, Jakarta Timur 13310', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ENFP', 'disc' => 'I']), 'ai_metrics' => json_encode(['turnover_risk' => 0.28, 'performance_score' => 8.0])],
            // Marketing Department (3)
            ['nik' => '12345678901234567898', 'no_ktp' => '3171234567890131', 'nama' => 'Ahmad Prasetyo', 'department' => 'Marketing', 'jabatan' => 'Marketing Manager', 'tempat_lahir' => 'Jakarta', 'tanggal_lahir' => Carbon::create(1989, 9, 25), 'tanggal_masuk' => Carbon::create(2017, 1, 15), 'jenis_kelamin' => 'L', 'dept_on_line' => 'Marketing', 'dept_on_line_awal' => 'Marketing', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 1, 'status_pajak' => 'K/1', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Gatot Subroto No. 789, Jakarta Selatan 12950', 'alamat_domisili' => 'Jalan Gatot Subroto No. 789, Jakarta Selatan 12950', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ESFP', 'disc' => 'I']), 'ai_metrics' => json_encode(['turnover_risk' => 0.18, 'performance_score' => 8.3])],
            ['nik' => '12345678901234567899', 'no_ktp' => '3171234567890132', 'nama' => 'Lisa Kusuma', 'department' => 'Marketing', 'jabatan' => 'Content Creator', 'tempat_lahir' => 'Yogyakarta', 'tanggal_lahir' => Carbon::create(1996, 4, 8), 'tanggal_masuk' => Carbon::create(2020, 8, 1), 'jenis_kelamin' => 'P', 'dept_on_line' => 'Marketing', 'dept_on_line_awal' => 'Marketing', 'status_pkwtt' => 'KONTRAK', 'status_keluarga' => 'Lajang', 'jumlah_anak' => 0, 'status_pajak' => 'TK/0', 'pendidikan' => 'D3', 'alamat_ktp' => 'Jalan Malioboro No. 100, Yogyakarta 55271', 'alamat_domisili' => 'Jalan Pramuka No. 400, Jakarta Timur 13140', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ENFP', 'disc' => 'S']), 'ai_metrics' => json_encode(['turnover_risk' => 0.45, 'performance_score' => 7.8])],
            ['nik' => '12345678901234567900', 'no_ktp' => '3171234567890133', 'nama' => 'Bambang Mujito', 'department' => 'Marketing', 'jabatan' => 'Digital Marketer', 'tempat_lahir' => 'Semarang', 'tanggal_lahir' => Carbon::create(1993, 11, 3), 'tanggal_masuk' => Carbon::create(2021, 2, 15), 'jenis_kelamin' => 'L', 'dept_on_line' => 'Marketing', 'dept_on_line_awal' => 'Marketing', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 2, 'status_pajak' => 'K/2', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Diponegoro No. 500, Semarang 50241', 'alamat_domisili' => 'Jalan Blora No. 150, Jakarta Selatan 12310', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ENFJ', 'disc' => 'I']), 'ai_metrics' => json_encode(['turnover_risk' => 0.22, 'performance_score' => 8.1])],
            // Operations (3)
            ['nik' => '12345678901234567901', 'no_ktp' => '3171234567890134', 'nama' => 'Gunawan Susanto', 'department' => 'Operations', 'jabatan' => 'Operations Manager', 'tempat_lahir' => 'Surabaya', 'tanggal_lahir' => Carbon::create(1986, 11, 30), 'tanggal_masuk' => Carbon::create(2014, 5, 15), 'jenis_kelamin' => 'L', 'dept_on_line' => 'Operations', 'dept_on_line_awal' => 'Operations', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 3, 'status_pajak' => 'K/3', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Ahmad Yani No. 567, Surabaya 60123', 'alamat_domisili' => 'Jalan Benda No. 150, Jakarta Selatan 12310', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ESTJ', 'disc' => 'D']), 'ai_metrics' => json_encode(['turnover_risk' => 0.05, 'performance_score' => 8.9])],
            ['nik' => '12345678901234567902', 'no_ktp' => '3171234567890135', 'nama' => 'Wati Hermawan', 'department' => 'Operations', 'jabatan' => 'Admin Staff', 'tempat_lahir' => 'Jakarta', 'tanggal_lahir' => Carbon::create(1995, 6, 17), 'tanggal_masuk' => Carbon::create(2021, 2, 1), 'jenis_kelamin' => 'P', 'dept_on_line' => 'Operations', 'dept_on_line_awal' => 'Operations', 'status_pkwtt' => 'KONTRAK', 'status_keluarga' => 'Lajang', 'jumlah_anak' => 0, 'status_pajak' => 'TK/0', 'pendidikan' => 'D3', 'alamat_ktp' => 'Jalan Jatinegara No. 100, Jakarta Timur 13310', 'alamat_domisili' => 'Jalan Jatinegara No. 100, Jakarta Timur 13310', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ISFJ', 'disc' => 'C']), 'ai_metrics' => json_encode(['turnover_risk' => 0.52, 'performance_score' => 7.5])],
            ['nik' => '12345678901234567903', 'no_ktp' => '3171234567890136', 'nama' => 'Hendra Wijaya', 'department' => 'Operations', 'jabatan' => 'Operations Coordinator', 'tempat_lahir' => 'Medan', 'tanggal_lahir' => Carbon::create(1991, 8, 11), 'tanggal_masuk' => Carbon::create(2020, 3, 1), 'jenis_kelamin' => 'L', 'dept_on_line' => 'Operations', 'dept_on_line_awal' => 'Operations', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 1, 'status_pajak' => 'K/1', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Merdeka No. 789, Medan 20112', 'alamat_domisili' => 'Jalan Gatot Subroto No. 100, Jakarta Selatan 12950', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ESTJ', 'disc' => 'S']), 'ai_metrics' => json_encode(['turnover_risk' => 0.19, 'performance_score' => 8.2])],
            // Sales (4)
            ['nik' => '12345678901234567904', 'no_ktp' => '3171234567890137', 'nama' => 'Slamet Ridho', 'department' => 'Sales', 'jabatan' => 'Sales Manager', 'tempat_lahir' => 'Jakarta', 'tanggal_lahir' => Carbon::create(1984, 1, 12), 'tanggal_masuk' => Carbon::create(2013, 9, 1), 'jenis_kelamin' => 'L', 'dept_on_line' => 'Sales', 'dept_on_line_awal' => 'Sales', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 2, 'status_pajak' => 'K/2', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Sudirman No. 456, Jakarta Selatan 12920', 'alamat_domisili' => 'Jalan Gatot Subroto No. 100, Jakarta Selatan 12950', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ESTP', 'disc' => 'D']), 'ai_metrics' => json_encode(['turnover_risk' => 0.20, 'performance_score' => 8.4])],
            ['nik' => '12345678901234567905', 'no_ktp' => '3171234567890138', 'nama' => 'Yenny Oktavia', 'department' => 'Sales', 'jabatan' => 'Sales Executive', 'tempat_lahir' => 'Bandung', 'tanggal_lahir' => Carbon::create(1991, 8, 3), 'tanggal_masuk' => Carbon::create(2018, 3, 15), 'jenis_kelamin' => 'P', 'dept_on_line' => 'Sales', 'dept_on_line_awal' => 'Sales', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 1, 'status_pajak' => 'K/1', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Gatot Subroto No. 200, Bandung 40272', 'alamat_domisili' => 'Jalan Terusan No. 500, Jakarta Barat 11210', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ENFJ', 'disc' => 'I']), 'ai_metrics' => json_encode(['turnover_risk' => 0.15, 'performance_score' => 8.6])],
            ['nik' => '12345678901234567906', 'no_ktp' => '3171234567890139', 'nama' => 'Eka Putra', 'department' => 'Sales', 'jabatan' => 'Sales Executive', 'tempat_lahir' => 'Surabaya', 'tanggal_lahir' => Carbon::create(1993, 5, 20), 'tanggal_masuk' => Carbon::create(2019, 10, 15), 'jenis_kelamin' => 'L', 'dept_on_line' => 'Sales', 'dept_on_line_awal' => 'Sales', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Lajang', 'jumlah_anak' => 0, 'status_pajak' => 'TK/0', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Gatot Subroto No. 456, Jakarta Selatan 12950', 'alamat_domisili' => 'Jalan Gatot Subroto No. 456, Jakarta Selatan 12950', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ESFP', 'disc' => 'I']), 'ai_metrics' => json_encode(['turnover_risk' => 0.38, 'performance_score' => 7.9])],
            ['nik' => '12345678901234567907', 'no_ktp' => '3171234567890140', 'nama' => 'Siti Rahayu', 'department' => 'Sales', 'jabatan' => 'Account Manager', 'tempat_lahir' => 'Yogyakarta', 'tanggal_lahir' => Carbon::create(1990, 12, 7), 'tanggal_masuk' => Carbon::create(2020, 6, 1), 'jenis_kelamin' => 'P', 'dept_on_line' => 'Sales', 'dept_on_line_awal' => 'Sales', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 2, 'status_pajak' => 'K/2', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Malioboro No. 300, Yogyakarta 55271', 'alamat_domisili' => 'Jalan Pramuka No. 600, Jakarta Timur 13140', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ENFJ', 'disc' => 'I']), 'ai_metrics' => json_encode(['turnover_risk' => 0.16, 'performance_score' => 8.5])],
            // QA (2)
            ['nik' => '12345678901234567908', 'no_ktp' => '3171234567890141', 'nama' => 'Bambang Sutrisno', 'department' => 'Quality Assurance', 'jabatan' => 'QA Lead', 'tempat_lahir' => 'Jakarta', 'tanggal_lahir' => Carbon::create(1988, 12, 10), 'tanggal_masuk' => Carbon::create(2016, 11, 1), 'jenis_kelamin' => 'L', 'dept_on_line' => 'Quality Assurance', 'dept_on_line_awal' => 'Quality Assurance', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 2, 'status_pajak' => 'K/2', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Kuningan No. 123, Jakarta Selatan 12950', 'alamat_domisili' => 'Jalan Kuningan No. 123, Jakarta Selatan 12950', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ISTJ', 'disc' => 'C']), 'ai_metrics' => json_encode(['turnover_risk' => 0.10, 'performance_score' => 8.5])],
            ['nik' => '12345678901234567909', 'no_ktp' => '3171234567890142', 'nama' => 'Tina Rahayu', 'department' => 'Quality Assurance', 'jabatan' => 'QA Tester', 'tempat_lahir' => 'Yogyakarta', 'tanggal_lahir' => Carbon::create(1997, 3, 22), 'tanggal_masuk' => Carbon::create(2021, 7, 15), 'jenis_kelamin' => 'P', 'dept_on_line' => 'Quality Assurance', 'dept_on_line_awal' => 'Quality Assurance', 'status_pkwtt' => 'KONTRAK', 'status_keluarga' => 'Lajang', 'jumlah_anak' => 0, 'status_pajak' => 'TK/0', 'pendidikan' => 'D3', 'alamat_ktp' => 'Jalan Malioboro No. 200, Yogyakarta 55271', 'alamat_domisili' => 'Jalan Pramuka No. 500, Jakarta Timur 13140', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'INFP', 'disc' => 'C']), 'ai_metrics' => json_encode(['turnover_risk' => 0.55, 'performance_score' => 7.6])],
            // Customer Service (2)
            ['nik' => '12345678901234567910', 'no_ktp' => '3171234567890143', 'nama' => 'Sulistyawan Dharma', 'department' => 'Customer Service', 'jabatan' => 'CS Manager', 'tempat_lahir' => 'Surabaya', 'tanggal_lahir' => Carbon::create(1989, 7, 14), 'tanggal_masuk' => Carbon::create(2015, 4, 1), 'jenis_kelamin' => 'L', 'dept_on_line' => 'Customer Service', 'dept_on_line_awal' => 'Customer Service', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 1, 'status_pajak' => 'K/1', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Ahmad Yani No. 456, Surabaya 60123', 'alamat_domisili' => 'Jalan Benda No. 250, Jakarta Selatan 12310', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ESFJ', 'disc' => 'I']), 'ai_metrics' => json_encode(['turnover_risk' => 0.12, 'performance_score' => 8.7])],
            ['nik' => '12345678901234567911', 'no_ktp' => '3171234567890144', 'nama' => 'Fitria Handoko', 'department' => 'Customer Service', 'jabatan' => 'CS Officer', 'tempat_lahir' => 'Jakarta', 'tanggal_lahir' => Carbon::create(1998, 9, 5), 'tanggal_masuk' => Carbon::create(2022, 1, 15), 'jenis_kelamin' => 'P', 'dept_on_line' => 'Customer Service', 'dept_on_line_awal' => 'Customer Service', 'status_pkwtt' => 'KONTRAK', 'status_keluarga' => 'Lajang', 'jumlah_anak' => 0, 'status_pajak' => 'TK/0', 'pendidikan' => 'D3', 'alamat_ktp' => 'Jalan Gatot Subroto No. 789, Jakarta Selatan 12950', 'alamat_domisili' => 'Jalan Gatot Subroto No. 789, Jakarta Selatan 12950', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ESFP', 'disc' => 'I']), 'ai_metrics' => json_encode(['turnover_risk' => 0.48, 'performance_score' => 7.7])],
            // Logistics (2)
            ['nik' => '12345678901234567912', 'no_ktp' => '3171234567890145', 'nama' => 'Eddy Purwanto', 'department' => 'Logistics', 'jabatan' => 'Logistics Manager', 'tempat_lahir' => 'Jakarta', 'tanggal_lahir' => Carbon::create(1987, 2, 28), 'tanggal_masuk' => Carbon::create(2014, 8, 1), 'jenis_kelamin' => 'L', 'dept_on_line' => 'Logistics', 'dept_on_line_awal' => 'Logistics', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 2, 'status_pajak' => 'K/2', 'pendidikan' => 'S1', 'alamat_ktp' => 'Jalan Sudirman No. 456, Jakarta Selatan 12920', 'alamat_domisili' => 'Jalan Sudirman No. 456, Jakarta Selatan 12920', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ESTJ', 'disc' => 'D']), 'ai_metrics' => json_encode(['turnover_risk' => 0.08, 'performance_score' => 8.8])],
            ['nik' => '12345678901234567913', 'no_ktp' => '3171234567890146', 'nama' => 'Khairul Anam', 'department' => 'Logistics', 'jabatan' => 'Warehouse Staff', 'tempat_lahir' => 'Bandung', 'tanggal_lahir' => Carbon::create(1996, 10, 18), 'tanggal_masuk' => Carbon::create(2020, 9, 1), 'jenis_kelamin' => 'L', 'dept_on_line' => 'Logistics', 'dept_on_line_awal' => 'Logistics', 'status_pkwtt' => 'KONTRAK', 'status_keluarga' => 'Lajang', 'jumlah_anak' => 0, 'status_pajak' => 'TK/0', 'pendidikan' => 'SMA', 'alamat_ktp' => 'Jalan Gatot Subroto No. 100, Bandung 40272', 'alamat_domisili' => 'Jalan Benda No. 600, Jakarta Selatan 12310', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ISFP', 'disc' => 'S']), 'ai_metrics' => json_encode(['turnover_risk' => 0.65, 'performance_score' => 7.2])],
            // Admin/Support (1)
            ['nik' => '12345678901234567914', 'no_ktp' => '3171234567890147', 'nama' => 'Margono Santoso', 'department' => 'Admin', 'jabatan' => 'Office Manager', 'tempat_lahir' => 'Jakarta', 'tanggal_lahir' => Carbon::create(1980, 6, 9), 'tanggal_masuk' => Carbon::create(2012, 1, 1), 'jenis_kelamin' => 'L', 'dept_on_line' => 'Admin', 'dept_on_line_awal' => 'Admin', 'status_pkwtt' => 'TETAP', 'status_keluarga' => 'Kawin', 'jumlah_anak' => 3, 'status_pajak' => 'K/3', 'pendidikan' => 'SMA', 'alamat_ktp' => 'Jalan Kuningan No. 789, Jakarta Selatan 12950', 'alamat_domisili' => 'Jalan Kuningan No. 789, Jakarta Selatan 12950', 'dokumen_pendukung' => json_encode(['foto_ktp' => 'path/to/ktp']), 'data_kepribadian' => json_encode(['mbti' => 'ISFJ', 'disc' => 'C']), 'ai_metrics' => json_encode(['turnover_risk' => 0.03, 'performance_score' => 8.9])],
        ];

        foreach ($employees as $employee) {
            Employee::create($employee);
        }
    }
}
